name: Setup env vars

decscription: Setup env vars for start a web server

runs:
  using: 'composite'
  steps:
    - name: Create a .env.test.local with vars
      shell: bash
      run: |
        echo "API_URL=http://localhost:8001" > .env.test.local
        echo "FIREBASE_API_KEY=test" >> .env.test.local
        echo "AUTH_DOMAIN_FIREBASE=test" >> .env.test.local
        echo "FIREBASE_DATABASE_URL=test" >> .env.test.local
        echo "PROJECT_ID=test" >> .env.test.local
        echo "STORAGE_BUCKET_FIREBASE=test" >> .env.test.local
        echo "MESSAGING_SENDER_ID=test" >> .env.test.local
        echo "APP_ID=test" >> .env.test.local
        echo "VAPID_KEY=test" >> .env.test.local
